Add Gasless NFT Minter Repo and StackBlitz
alchemyplatform/aa-sdk pull request #199
Opened 2023-11-01 19:06 UTC by AlvaroLuken

2023-11-01 19:23 UTC, avasisht23 reviewed
change looks good - can you rebase on development branch + lint the file

2023-11-06 00:40 UTC, denniswon requested changes
please update the pr rebased to development branch

2023-11-06 00:40 UTC, denniswon commented on examples/aa-gasless-nft-minter
Can you not add as a submodule like other examples?

2023-11-26 18:42 UTC, avasisht23 commented
closing in favor of adding directly to examples folder after code review

2023-11-26 18:42 UTC, closed without merging