feat: make entire format of our doc site consistent and concise
alchemyplatform/aa-sdk pull request #215
Opened 2023-11-06 20:32 UTC by denniswon

2023-11-06 22:28 UTC, avasisht23 requested changes
let's keep the intro/overview docs as a separate item. 

this was feedback from Will that it's unintuitive to click on the section header and expect a page, vs. having it be more explicit and visible as a standalone link with something like "Overview"

2023-11-07 00:15 UTC, denniswon commented on site/smart-accounts/accounts/light-account.md
This file is already reviewed.

2023-11-07 00:42 UTC, denniswon commented
@avasisht23 separated the pr with https://github.com/alchemyplatform/aa-sdk/pull/217

I will accommodate your comment above on that pr.

2023-11-07 15:53 UTC, avasisht23 approved these changes
just relint the config.ts folder. missing an EOF newline.

2023-11-07 17:32 UTC, merged